<?php require('./layout/header.php') ?>

			<main>
				<h2>Home</h2>
				<br>
				<img src="images/img-01.png">
				<p class="ejemplo">	
					Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras finibus enim orci, nec semper nibh ornare vel. Curabitur ut felis ac ex consequat dictum at quis mauris. Ut venenatis euismod nunc id pellentesque. Vivamus fringilla auctor nulla eu lacinia. Nulla orci arcu, vulputate at iaculis et, vehicula eu magna. Duis pretium consectetur magna eget volutpat. Sed dui velit, lobortis sit amet sapien et, congue finibus nulla. Curabitur placerat, ante in ultrices vulputate, magna justo iaculis sem, ut vehicula diam libero a dolor. Vivamus vestibulum neque eget vestibulum convallis. Aliquam nec iaculis sem. Integer finibus bibendum ex, a consectetur velit mattis non. Nunc maximus nec metus ut interdum. Mauris ac erat sem. Duis feugiat, mauris a luctus tempor, risus ipsum aliquam augue, ac congue nibh lorem quis quam. In hac habitasse platea dictumst. Sed consectetur pharetra sem non facilisis. In sit amet tortor mollis, dictum diam non, dapibus odio. Fusce nec posuere ex, nec hendrerit urna. Donec suscipit congue viverra. Etiam viverra tincidunt elit, non hendrerit sapien porta ac. Vivamus orci tellus, egestas in viverra quis, posuere non lectus. Nullam metus risus, interdum a pretium a, egestas feugiat ipsum. Aliquam dui diam, blandit a ultricies id, ornare ornare nulla. Pellentesque urna est, accumsan non nibh sit amet, accumsan suscipit dui. Mauris viverra euismod orci, et consequat justo laoreet a. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Duis tincidunt eleifend fringilla. Integer eu diam venenatis, tempus eros eget, semper arcu. Aenean pretium lacinia risus, eu tempus massa. Aenean pellentesque fringilla velit in tincidunt. Morbi vel ex viverra, maximus mi vitae, aliquam mi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nulla elit elit, mollis in volutpat at, auctor id neque. Donec nulla odio, cursus ut porta sit amet, suscipit sed mauris. Integer faucibus rhoncus nisl ut consequat. Nulla quis semper elit, non vehicula eros. Aenean nec viverra dui. Donec malesuada sed nisi at tempus. Pellentesque ut mi sapien. Fusce rhoncus facilisis euismod. Pellentesque quis risus nisi. Nullam vitae accumsan orci, a molestie enim. Aliquam id venenatis tellus, elementum maximus metus. Nulla in dignissim elit. Nulla tempus felis ante, eu finibus purus posuere vel. Donec congue odio id sollicitudin congue. Morbi nec luctus turpis. Sed quis interdum nibh. Curabitur lobortis a magna non rhoncus. Integer eget sagittis mi, sed mollis elit. Etiam ut tortor vitae nulla ultrices semper. Proin tristique placerat dictum. Nunc mollis metus in nibh pharetra eleifend. Quisque ac dui cursus, mollis quam at, mollis mi. Sed vel massa pharetra nibh venenatis aliquam. Aenean vel nulla auctor, scelerisque felis sed, bibendum neque. Ut consequat semper felis, in euismod magna. 
				</p>
			</main>

			<?php require('./layout/aside.php') ?>

<?php require('./layout/footer.php') ?>
